In [4]:
import pandas as pd

path = '/content/drive/MyDrive/Học máy cơ bản/diabetes.csv'

df = pd.read_csv(path)

#1: Đọc file diabetes.csv và hiển thị 10 bản ghi đầu tiên.
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [7]:
#2: Hiển thị 10 bản ghi ngẫu nhiên trong file diabetes.csv.
df.sample(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
21,8,99,84,0,0,35.4,0.388,50,0
609,1,111,62,13,182,24.0,0.138,23,0
692,2,121,70,32,95,39.1,0.886,23,0
597,1,89,24,19,25,27.8,0.559,21,0
571,2,130,96,0,0,22.6,0.268,21,0
37,9,102,76,37,0,32.9,0.665,46,1
477,7,114,76,17,110,23.8,0.466,31,0
295,6,151,62,31,120,35.5,0.692,28,0
311,0,106,70,37,148,39.4,0.605,22,0
379,0,93,100,39,72,43.4,1.021,35,0

In [12]:
#3: Hiển thị số người bị mắc bệnh tiểu đường và số người không bị.
x = (df['Outcome'] == 1).sum()
y = (df['Outcome'] == 0).sum()
print("Số người bị mắc bệnh tiểu đường: ", x)
print("Số người không bị: ", y)

Số người bị mắc bệnh tiểu đường:  268
Số người không bị:  500

In [16]:
#4: Hiển thị tỉ lệ phần trăm số người bị mắc bệnh và không mắc bệnh.
x = (df['Outcome'] == 1).sum()
y = (df['Outcome'] == 0).sum()
tong = x + y
x = (x / tong) * 100
y = (y / tong) * 100
print("Tỷ lệ % người bị mắc bệnh tiểu đường: ", x, "%")
print("Tỷ lệ % người không bị: ", y, "%")

Tỷ lệ % người bị mắc bệnh tiểu đường:  34.89583333333333 %
Tỷ lệ % người không bị:  65.10416666666666 %

In [22]:
#5: Đếm và hiển thị số người trên 50 tuổi.
x = (df['Age']>50).sum()
print("Số người trên 50 tuổi: ", x)
df[df.Age>50]

Số người trên 50 tuổi:  Pregnancies                  265.000
Glucose                     5470.000
BloodPressure               3254.000
SkinThickness                432.000
Insulin                     1456.000
BMI                         1221.800
DiabetesPedigreeFunction      19.549
Age                         2607.000
Outcome                        0.000
dtype: float64

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76,27,0,35.6,0.378,52,1
734,2,105,75,0,0,23.3,0.560,53,0
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [31]:
#6: Đếm và hiển thị số người trên 50 tuổi mà không bị mắc bệnh tiểu đường.
x = df[(df['Age']>50) & (df['Outcome'] == 0)]
print("Số người trên 50 tuổi không bị mắc tiểu đường: ", len(x))
x

Số người trên 50 tuổi không bị mắc tiểu đường:  43

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
12,10,139,80,0,0,27.1,1.441,57,0
28,13,145,82,19,110,22.2,0.245,57,0
30,5,109,75,26,0,36.0,0.546,60,0
67,2,109,92,0,0,42.7,0.845,54,0
123,5,132,80,0,0,26.8,0.186,69,0
140,3,128,78,0,0,21.1,0.268,55,0
148,5,147,78,0,0,33.7,0.218,65,0
204,6,103,72,32,190,37.7,0.324,55,0
212,7,179,95,31,0,34.2,0.164,60,0
223,7,142,60,33,190,28.8,0.687,61,0
263,3,142,80,15,0,32.4,0.200,63,0
274,13,106,70,0,0,34.2,0.251,52,0
278,5,114,74,0,0,24.9,0.744,57,0
285,7,136,74,26,135,26.0,0.647,51,0
294,0,161,50,0,0,21.9,0.254,65,0
299,8,112,72,0,0,23.6,0.840,58,0
344,8,95,72,0,0,36.8,0.485,57,0
361,5,158,70,0,0,29.8,0.207,63,0
362,5,103,108,37,0,39.2,0.305,65,0
401,6,137,61,0,0,24.2,0.151,55,0
453,2,119,0,0,0,19.6,0.832,72,0
456,1,135,54,0,0,26.7,0.687,62,0
459,9,134,74,33,60,25.9,0.460,81,0
475,0,137,84,27,0,27.3,0.231,59,0
479,4,132,86,31,0,28.0,0.419,63,0
487,0,173,78,32,265,46.5,1.159,58,0
489,8,194,80,0,0,26.1,0.551,67,0
495,6,166,74,0,0,26.6,0.304,66,0
509,8,120,78,0,0,25.0,0.409,64,0
512,9,91,68,0,0,24.2,0.200,58,0
517,7,125,86,0,0,37.6,0.304,51,0
519,6,129,90,7,326,19.6,0.582,60,0
537,0,57,60,0,0,21.7,0.735,67,0
552,6,114,88,0,0,27.8,0.247,66,0
557,8,110,76,0,0,27.8,0.237,58,0
582,12,121,78,17,0,26.5,0.259,62,0
658,11,127,106,0,0,39.0,0.190,51,0
660,10,162,84,0,0,27.7,0.182,54,0
674,8,91,82,0,0,35.6,0.587,68,0
684,5,136,82,0,0,0.0,0.640,69,0
717,10,94,72,18,0,23.1,0.595,56,0
734,2,105,75,0,0,23.3,0.560,53,0
763,10,101,76,48,180,32.9,0.171,63,0

In [39]:
#7: Đếm và hiển thị số người trên 50 tuổi, mang thai ít nhất 2 lần mà không bị mắc bệnh tiểu đường.
x = df[(df['Age']>50) & (df['Outcome'] == 0) & (df['Pregnancies']>=2)]
print("Số người trên 50 tuổi mang thai ít nhất 2 lần không bị mắc tiểu đường: ", len(x))
x

Số người trên 50 tuổi mang thai ít nhất 2 lần không bị mắc tiểu đường:  38

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
12,10,139,80,0,0,27.1,1.441,57,0
28,13,145,82,19,110,22.2,0.245,57,0
30,5,109,75,26,0,36.0,0.546,60,0
67,2,109,92,0,0,42.7,0.845,54,0
123,5,132,80,0,0,26.8,0.186,69,0
140,3,128,78,0,0,21.1,0.268,55,0
148,5,147,78,0,0,33.7,0.218,65,0
204,6,103,72,32,190,37.7,0.324,55,0
212,7,179,95,31,0,34.2,0.164,60,0
223,7,142,60,33,190,28.8,0.687,61,0
263,3,142,80,15,0,32.4,0.200,63,0
274,13,106,70,0,0,34.2,0.251,52,0
278,5,114,74,0,0,24.9,0.744,57,0
285,7,136,74,26,135,26.0,0.647,51,0
299,8,112,72,0,0,23.6,0.840,58,0
344,8,95,72,0,0,36.8,0.485,57,0
361,5,158,70,0,0,29.8,0.207,63,0
362,5,103,108,37,0,39.2,0.305,65,0
401,6,137,61,0,0,24.2,0.151,55,0
453,2,119,0,0,0,19.6,0.832,72,0
459,9,134,74,33,60,25.9,0.460,81,0
479,4,132,86,31,0,28.0,0.419,63,0
489,8,194,80,0,0,26.1,0.551,67,0
495,6,166,74,0,0,26.6,0.304,66,0
509,8,120,78,0,0,25.0,0.409,64,0
512,9,91,68,0,0,24.2,0.200,58,0
517,7,125,86,0,0,37.6,0.304,51,0
519,6,129,90,7,326,19.6,0.582,60,0
552,6,114,88,0,0,27.8,0.247,66,0
557,8,110,76,0,0,27.8,0.237,58,0
582,12,121,78,17,0,26.5,0.259,62,0
658,11,127,106,0,0,39.0,0.190,51,0
660,10,162,84,0,0,27.7,0.182,54,0
674,8,91,82,0,0,35.6,0.587,68,0
684,5,136,82,0,0,0.0,0.640,69,0
717,10,94,72,18,0,23.1,0.595,56,0
734,2,105,75,0,0,23.3,0.560,53,0
763,10,101,76,48,180,32.9,0.171,63,0

In [41]:
#8: Đếm xem có bao nhiêu người mang thai ít nhất 3 lần.
x = df[df['Pregnancies']>=3]
print("Số người mang thai ít nhất 3 lần: ", len(x))
x

Số người mang thai ít nhất 3 lần:  419

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
...,...,...,...,...,...,...,...,...,...
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
765,5,121,72,23,112,26.2,0.245,30,0

In [40]:
#9: Đếm xem có bao nhiêu người trên 40 tuổi và mang thai ít nhất 2 lần.
x = df[(df['Age']>40) & (df['Pregnancies']>=2)]
print("Số người trên 40 tuổi mang thai ít nhất 2 lần: ", len(x))
x

Số người trên 40 tuổi mang thai ít nhất 2 lần:  169

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
749,6,162,62,0,0,24.3,0.178,50,1
754,8,154,78,32,0,32.4,0.443,45,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
763,10,101,76,48,180,32.9,0.171,63,0